name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip
        pip3 install buildozer
        
    - name: Build APK with Buildozer
      run: |
        buildozer init
        # 创建buildozer.spec配置
        cat > buildozer.spec << EOF
[app]
title = 漫画阅读器
package.name = mangareader
package.domain = com.yourname

source.dir = .
source.include_exts = py,png,jpg,jpeg,kv,atlas,ttf

version = 0.1
requirements = python3,kivy

orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2

[android]
api = 33
minapi = 21
android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
EOF
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: manga-reader-apk
        path: bin/*.apk
